---

plugins:
  - import

# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  node: true

extends:
  - 'airbnb-base'

rules:
  no-console: 0
  import/extensions: 0
  "import/no-extraneous-dependencies": ["error", {"devDependencies": true}]